title: STICK NO BILLS FONT
desc:  STICK NO BILLS - is the bespoke typeface of Stick No Bills™ Poster Gallery in Galle, Sri Lanka.
baseurl:  /stick-no-bills-font
font_name: StickNoBills
family_name: StickNoBills
family_weight_1: Light
family_weight_2: Bold
thumb_url:
glyphs: අ ඉ ඊ උ එ ඔ ක ඛ ග ඝ ච ට ඩ න ප ව හ
string_sinhala: දසවසර නගරබදවය කම කනමදය ගතවන කනකර සමරන සලපතළ දනට කපල ළය සරසන වනරතන රත සවන යටවන පරවල වටය නගරබදවය වදන සතයකට අද මටටම සමර ගතකර නගරබදවය ගතකර අගනගරය ගස සම අපර අසමසම කටට බණ අයකරන රටවට අ පරණ පතක නගරබදවය නගරබදවය පණමට නවකවදය නගරබදවය මත වළදන යට රටවල නවවන පවසවනව මලල කලමතය නගරබදවය අලවන බරපතල කළබව පලස කතරගම අතපත වනනඅතර නවක
string_latin: novas snappiness idea viands edison avion iodopsins ass nose peon spininess eve sod dividends possisdendi denda assidaean pep anapes aped dispossessed vendean pinons despises is diseasedness desidiose seas a pain sod do peep anne openendedness novas spoon evase do nee spondean en spondean saanen on seasides andia ion dissava poseidon is as indivision nonpossessive avidnesses an asap vinea pinnas pips dispassion iso aid save sane div en possessedness ped



safe: false
lsi: false
pygments: true


# About/contact
author:
  name:              Pathum Egodawatta
  url:               https://twitter.com/pathumego
  email:             pathum@mooniak.com

# Custom vars
version:             0.0.1

exclude:
  - README.md
