title: STICK NO BILLS FONT
desc:  STICK NO BILLS - is the bespoke typeface of Stick No Bills™ Poster Gallery in Galle, Sri Lanka.
baseurl:  /stick-no-bills-font
font_name: StickNoBills
family_name: StickNoBills
family_weight_1: Light
family_weight_2: Bold
thumb_url:
glyphs: අ ඉ ඊ උ එ ඔ ක ඛ ග ඝ ච ට ඩ න ප ව හ
string_sinhala: නවවන අටක ඉනට එවන එන චවන අගවන අපව කඩන කනකට ගහක උනට අඩපන එට ගහ අනන ඔප නවවන අගවන ඉඩකඩ අහක එක කනකට පටවන අක වගව අහගන අග අඩපන වඩවන ගහක අට අටවන නව කහ උගහට නටවන පවට අඩපන කවට කටවහ එ ච අගවන නගන පනවන පටක වගව කටට කටහඩ ඊ එකග පටවන කටට අඩපන ගන අ වට නටවන ඊටට අහන ඉඩකඩ චනට ඔපවන එකට අගවන චන අටවක අඩක උප අගවන වඩවන අඩපන කටවහ නවක අක වඩ පනවන පවකට කව කනකට ඝන වනට අගවන උපන හඩ පහට නටන ඔපවන චන අටක උඩ ඉව කවන පටවන එකට අඩ නවවන අහගන නවන අහගන පනවන පටවන එකග උපන චන වඩවන පවකට පවකට වඩ පටවන අගවන ඔපවන ටක හඩ ගහන කන ඉනට ක අටවක උගහට කන උහන කටවහ කවට පනවන ග ඉඩක නටවන එකක කහන ඉඩක එට උපන උගහට
string_latin: Researchers from the journal reviewed a host of data and evidence published on insect-bite treatments. It concluded in many cases treatments for insect bites had not actually been tested for such purposes. It said medical help should clearly be sought if serious symptoms, such as infections or anaphylactic shock, developed. But it said for simple bites a flannel or cloth soaked in cold water often worked best - despite advice from official bodies, such as NHS Choices, suggesting treatments should be used. David Phizackerley, the deputy editor of the journal, said: “People are using these treatments so they should know there is no evidence they work. [Most] bites will get better on their own.” Hungry bugs placed on shaved arms were more likely to try to feed compared with those on unshaved arms, the journal Biology Letters reported. Researchers say the hair slows down the bed bugs and warns the victim. Pest controllers say the UK is currently experiencing a steep rise in the number of bed bug infestations. Prof Michael Siva-Jothy, from Sheffield University's Department of Animal and Plant Sciences, recruited 29 brave volunteers to test the theory further, watching the bedbugs as they found a place to feed and removing them only as they were about to bite. This tallies with other studies which look at how humans came to be relatively less hairy than apes. He found that more layers of both longer visible hairs and finer, “vellus” hairs near the surface appeared to work as a deterrent to the insects, with the finer hairs also acting as an early warning system. Continue reading the main story “Start Quote If you have a heavy coat of long thick hairs it is easier for parasites to hide” Professor Siva-Jothy Sheffield University Prof Siva-Jothy said: “Our findings show that more body hairs mean better detection of parasites - the hairs have nerves attached to them and provide us 


safe: false
lsi: false
pygments: true


# About/contact
author:
  name:              Pathum Egodawatta
  url:               https://twitter.com/pathumego
  email:             pathum@mooniak.com

# Custom vars
version:             0.0.1

exclude:
  - README.md
